#!/bin/bash
echo "=> Building runner"
docker run --rm \
    -v "$PWD":/usr/src/mcrunner \
    -w /usr/src/mcrunner \
    -e GOOS=linux \
    -e GOARCH=amd64 \
    golang:1.8 \
    GOPATH=/usr/src/mcrunner & go build -v -o mcrunner.exe main
