#!/bin/bash
echo "=> Building runner"
docker run --rm \
    -it \
    -v "$PWD":/usr/src/mcrunner \
    -w /usr/src/mcrunner \
    -e GOOS=linux \
    -e GOARCH=amd64 \
    golang:latest \
    bash
GOPATH=$PWD
go build -v -o mcrunner.exe main
